name: release

on:
  push:
    tags:
      - v*

jobs:

  release-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: latest

      - name: install dependencies
        run: pnpm install

      - name: get version
        id: version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: build
        run: pnpm build

      - name: publish gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          cname: metacubexd.xireiki.com
          commit_message: ${{ steps.version.outputs.VERSION }}

      - name: compress dist
        run: tar czvf compressed-dist.tgz -C dist .

      - name: attach github release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: compressed-dist.tgz
          tag_name: ${{ steps.version.outputs.VERSION }}
